from setuptools import setup
setup(
    name='joes-tools',
    version='0.1',
    packages=find_packages(exclude=['sandbox*', 'tests*']),
    include_package_data=True,
    install_requires=[
        'altgraph==0.16.1',
        'backports.functools-lru-cache==1.5',
        'Click==7.0',
        'cycler==0.10.0',
        'dis3==0.1.3',
        'enum34==1.1.6',
        'Flask==1.0.2',
        'future==0.17.1',
        'geojson==2.4.1',
        'gunicorn==19.9.0',
        'itsdangerous==1.1.0',
        'Jinja2==2.10',
        'kiwisolver==1.0.1',
        'macholib==1.11',
        'MarkupSafe==1.1.0',
        'matplotlib==2.2.3',
        'numexpr==2.6.9',
        'numpy==1.15.4',
        'odin==1.4.0',
        'pandas==0.24.0',
        'pefile==2019.4.18',
        'PyInstaller==3.4',
        'pyparsing==2.3.1',
        'python-dateutil==2.7.5',
        'pytz==2018.9',
        'pywin32-ctypes==0.2.0',
        'scipy==1.2.0',
        'six==1.12.0',
        'tables==3.4.4',
        'typing==3.6.6',
        'Werkzeug==0.14.1'
    ],
    url='https://github.com/FishAndSauce/joes-tools',
    license='Yeah',
    author='Joe Wyndham',
    author_email='joseph.wyndham@gmail.com',
    description='YEah'
)

